[functions.whatsapp-webhook]
verify_jwt = false

[functions.extract-transfer-amount]
verify_jwt = false

[functions.green-api-webhook]
verify_jwt = false

[functions.extract-print-receipt]
verify_jwt = false

[functions.finalize-whatsapp-groups]
verify_jwt = false
